import type { FunctionDef, ParsedInterface, ProjectOptions } from "../types.ts";

export function generateCppSafeWrapper(parsed: ParsedInterface, options?: ProjectOptions): string {
  const ns = options?.namespace || "SafeApi";
  const lines: string[] = [];

  lines.push("// ============================================================================");
  lines.push(`// Auto-generated Modern C++20 Safe Wrapper Interface`);
  lines.push(`// Generated by IF-Creator (Source Language: ${parsed.sourceLanguage})`);
  lines.push("// ============================================================================");
  lines.push("#pragma once");
  lines.push("");
  lines.push("#include <string>");
  lines.push("#include <vector>");
  lines.push("#include <memory>");
  lines.push("#include <optional>");
  lines.push("#include <stdexcept>");
  lines.push("#include <functional>");
  lines.push("#include <string_view>");
  lines.push("");

  if (parsed.sourceLanguage === "c") {
    lines.push('extern "C" {');
    lines.push('  #include "low_level_api.h"');
    lines.push('}');
    lines.push("");
  }

  lines.push(`namespace ${ns} {`);
  lines.push("");
  lines.push("  class ApiException : public std::runtime_error {");
  lines.push("  public:");
  lines.push("    explicit ApiException(const std::string& msg) : std::runtime_error(msg) {}");
  lines.push("  };");
  lines.push("");

  // Generate safe wrapper class
  const className = `${parsed.name || "Client"}Wrapper`;
  lines.push(`  class ${className} {`);
  lines.push("  public:");
  lines.push(`    ${className}() = default;`);
  lines.push(`    ~${className}() = default;`);
  lines.push("");

  for (const fn of parsed.functions) {
    if (fn.doc) {
      lines.push("    /**");
      for (const d of fn.doc.split("\n")) {
        lines.push(`     * ${d}`);
      }
      lines.push("     */");
    }

    const retTypeCpp = mapTypeToCpp(fn.returnType.type, fn.returnType.rawType);
    const paramsCpp = fn.parameters.map((p) => {
      const cppType = mapTypeToCppParam(p.type, p.rawType);
      return `${cppType} ${p.name}${p.defaultValue ? ` = ${p.defaultValue}` : ""}`;
    }).join(", ");

    lines.push(`    ${retTypeCpp} ${fn.name}(${paramsCpp}) {`);
    
    // Safety assertions / pre-checks
    for (const p of fn.parameters) {
      if (p.isPointer && !p.defaultValue) {
        lines.push(`      if (${p.name} == nullptr) {`);
        lines.push(`        throw ApiException("Parameter '${p.name}' cannot be null");`);
        lines.push(`      }`);
      }
    }

    // Call underlying implementation
    const callArgs = fn.parameters.map((p) => {
      if (p.type === "string" && parsed.sourceLanguage === "c") {
        return `${p.name}.c_str()`;
      }
      return p.name;
    }).join(", ");

    if (fn.returnType.isVoid) {
      lines.push(`      ::${fn.name}(${callArgs});`);
    } else {
      lines.push(`      auto result = ::${fn.name}(${callArgs});`);
      if (fn.returnType.type === "string" && parsed.sourceLanguage === "c") {
        lines.push(`      if (!result) return "";`);
        lines.push(`      return std::string(result);`);
      } else {
        lines.push(`      return result;`);
      }
    }

    lines.push("    }");
    lines.push("");
  }

  lines.push("  };");
  lines.push("");
  lines.push(`} // namespace ${ns}`);

  return lines.join("\n");
}

function mapTypeToCpp(normalized: string, raw: string): string {
  switch (normalized) {
    case "integer": return "int64_t";
    case "number": return "double";
    case "string": return "std::string";
    case "boolean": return "bool";
    case "void": return "void";
    case "array": return "std::vector<std::string>";
    case "object": return "std::shared_ptr<void>";
    default: return raw || "void*";
  }
}

function mapTypeToCppParam(normalized: string, raw: string): string {
  switch (normalized) {
    case "integer": return "int64_t";
    case "number": return "double";
    case "string": return "std::string_view";
    case "boolean": return "bool";
    case "array": return "const std::vector<std::string>&";
    default: return raw || "const void*";
  }
}
