import type { FunctionDef, ParsedInterface, ProjectOptions } from "../types.ts";

export function generateMcpServer(parsed: ParsedInterface, options?: ProjectOptions): string {
  const serverName = options?.targetMcpServerName || `${(parsed.name || "custom-api").toLowerCase().replace(/[^a-z0-9_-]/g, "-")}-mcp`;
  const lines: string[] = [];

  lines.push("// ============================================================================");
  lines.push(`// Auto-generated Model Context Protocol (MCP) Server`);
  lines.push(`// Generated by IF-Creator for ${parsed.name}`);
  lines.push("// Protocol: MCP (Model Context Protocol) 2024-11-05 / 2025");
  lines.push("// ============================================================================");
  lines.push("");
  lines.push('import { Server } from "@modelcontextprotocol/sdk/server/index.js";');
  lines.push('import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";');
  lines.push('import { CallToolRequestSchema, ListToolsRequestSchema } from "@modelcontextprotocol/sdk/types.js";');
  lines.push("");

  // Build tools list
  lines.push("export const TOOLS = [");
  for (const fn of parsed.functions) {
    const properties: Record<string, any> = {};
    const required: string[] = [];

    for (const p of fn.parameters) {
      properties[p.name] = {
        type: mapTypeToMcpSchema(p.type),
        description: p.doc || `Parameter ${p.name} (${p.rawType})`,
      };
      if (!p.isOptional) {
        required.push(p.name);
      }
    }

    lines.push("  {");
    lines.push(`    name: "${fn.name}",`);
    lines.push(`    description: ${JSON.stringify(fn.doc || `Execute native interface operation ${fn.name}`)},`);
    lines.push("    inputSchema: {");
    lines.push('      type: "object",');
    lines.push(`      properties: ${JSON.stringify(properties, null, 8).replace(/^/gm, "      ").trim()},`);
    lines.push(`      required: ${JSON.stringify(required)},`);
    lines.push("    },");
    lines.push("  },");
  }
  lines.push("];");
  lines.push("");

  // Server Initialization
  lines.push(`export function createMcpServer(apiClient?: any) {`);
  lines.push("  const server = new Server(");
  lines.push("    {");
  lines.push(`      name: "${serverName}",`);
  lines.push('      version: "1.0.0",');
  lines.push("    },");
  lines.push("    {");
  lines.push("      capabilities: {");
  lines.push("        tools: {},");
  lines.push("      },");
  lines.push("    }");
  lines.push("  );");
  lines.push("");

  lines.push("  server.setRequestHandler(ListToolsRequestSchema, async () => {");
  lines.push("    return { tools: TOOLS };");
  lines.push("  });");
  lines.push("");

  lines.push("  server.setRequestHandler(CallToolRequestSchema, async (request) => {");
  lines.push("    const { name, arguments: args } = request.params;");
  lines.push("");
  lines.push("    try {");
  lines.push("      switch (name) {");

  for (const fn of parsed.functions) {
    lines.push(`        case "${fn.name}": {`);
    const argList = fn.parameters.map((p) => `args?.${p.name}`).join(", ");
    lines.push(`          // Dispatch to underlying implementation or gateway`);
    lines.push(`          const result = apiClient ? await apiClient.${fn.name}(${argList ? `args` : ""}) : { status: "executed", function: "${fn.name}", args };`);
    lines.push("          return {");
    lines.push("            content: [");
    lines.push("              {");
    lines.push('                type: "text",');
    lines.push("                text: JSON.stringify(result, null, 2),");
    lines.push("              },");
    lines.push("            ],");
    lines.push("          };");
    lines.push("        }");
  }

  lines.push("        default:");
  lines.push("          return {");
  lines.push("            content: [");
  lines.push("              {");
  lines.push('                type: "text",');
  lines.push('                text: `Unknown tool requested: ${name}`,');
  lines.push("              },");
  lines.push("            ],");
  lines.push("            isError: true,");
  lines.push("          };");
  lines.push("      }");
  lines.push("    } catch (error: any) {");
  lines.push("      return {");
  lines.push("        content: [");
  lines.push("          {");
  lines.push('            type: "text",');
  lines.push("            text: `Error executing ${name}: ${error.message || String(error)}`,");
  lines.push("          },");
  lines.push("        ],");
  lines.push("        isError: true,");
  lines.push("      };");
  lines.push("    }");
  lines.push("  });");
  lines.push("");
  lines.push("  return server;");
  lines.push("}");
  lines.push("");

  lines.push("// Standalone CLI entrypoint");
  lines.push('if (import.meta.main || (typeof process !== "undefined" && process.argv && process.argv[1] === import.meta.url)) {');
  lines.push("  const server = createMcpServer();");
  lines.push("  const transport = new StdioServerTransport();");
  lines.push("  await server.connect(transport);");
  lines.push(`  console.error("${serverName} MCP server running on stdio");`);
  lines.push("}");

  return lines.join("\n");
}

function mapTypeToMcpSchema(normalized: string): string {
  switch (normalized) {
    case "integer": return "integer";
    case "number": return "number";
    case "string": return "string";
    case "boolean": return "boolean";
    case "array": return "array";
    case "object": return "object";
    default: return "string";
  }
}
