import type { FunctionDef, ParsedInterface, ProjectOptions } from "../types.ts";

export function generateTsClient(parsed: ParsedInterface, options?: ProjectOptions): string {
  const className = `${capitalize(parsed.name || "ApiClient")}`;
  const prefix = options?.apiPrefix || "/api/v1";
  const lines: string[] = [];

  lines.push("// ============================================================================");
  lines.push(`// Auto-generated TypeScript / JavaScript Client SDK`);
  lines.push(`// Generated by IF-Creator for ${parsed.name}`);
  lines.push("// ============================================================================");
  lines.push("");
  lines.push("export class ApiException extends Error {");
  lines.push("  constructor(message: string, public status?: number, public details?: unknown) {");
  lines.push("    super(message);");
  lines.push('    this.name = "ApiException";');
  lines.push("  }");
  lines.push("}");
  lines.push("");

  // Interface definitions for request/response
  for (const fn of parsed.functions) {
    const reqName = `${capitalize(fn.name)}Params`;
    lines.push(`export interface ${reqName} {`);
    for (const p of fn.parameters) {
      const tsType = mapTypeToTs(p.type);
      const opt = p.isOptional ? "?" : "";
      const doc = p.doc ? `  /** ${p.doc} */\n` : "";
      lines.push(`${doc}  ${p.name}${opt}: ${tsType};`);
    }
    lines.push("}");
    lines.push("");

    const resType = fn.returnType.isVoid ? "void" : mapTypeToTs(fn.returnType.type);
    lines.push(`export type ${capitalize(fn.name)}Result = ${resType};`);
    lines.push("");
  }

  // Client Class
  lines.push(`export interface ${className}Config {`);
  lines.push("  baseUrl?: string;");
  lines.push("  headers?: Record<string, string>;");
  lines.push("  fetch?: typeof fetch;");
  lines.push("}");
  lines.push("");
  lines.push(`export class ${className} {`);
  lines.push("  private baseUrl: string;");
  lines.push("  private headers: Record<string, string>;");
  lines.push("  private customFetch: typeof fetch;");
  lines.push("");
  lines.push(`  constructor(config: ${className}Config = {}) {`);
  lines.push(`    this.baseUrl = (config.baseUrl || "http://localhost:${options?.restPort || 8000}").replace(/\\/+$/, "");`);
  lines.push("    this.headers = {");
  lines.push('      "Content-Type": "application/json",');
  lines.push("      ...(config.headers || {}),");
  lines.push("    };");
  lines.push("    this.customFetch = config.fetch || globalThis.fetch.bind(globalThis);");
  lines.push("  }");
  lines.push("");

  // Methods
  for (const fn of parsed.functions) {
    const reqName = `${capitalize(fn.name)}Params`;
    const resType = `${capitalize(fn.name)}Result`;

    if (fn.doc) {
      lines.push("  /**");
      for (const d of fn.doc.split("\n")) {
        lines.push(`   * ${d}`);
      }
      lines.push("   */");
    }

    const hasParams = fn.parameters.length > 0;
    const paramSig = hasParams ? `params: ${reqName}` : `params: ${reqName} = {}`;

    lines.push(`  async ${fn.name}(${paramSig}): Promise<${resType}> {`);
    lines.push(`    const url = \`\${this.baseUrl}${prefix}/${fn.name}\`;`);
    lines.push("    try {");
    lines.push("      const res = await this.customFetch(url, {");
    lines.push('        method: "POST",');
    lines.push("        headers: this.headers,");
    lines.push("        body: JSON.stringify(params),");
    lines.push("      });");
    lines.push("");
    lines.push("      if (!res.ok) {");
    lines.push("        const errorBody = await res.json().catch(() => ({ error: res.statusText }));");
    lines.push(`        throw new ApiException(errorBody.error || \`HTTP \${res.status}\`, res.status, errorBody);`);
    lines.push("      }");
    lines.push("");
    if (fn.returnType.isVoid) {
      lines.push("      return;");
    } else {
      lines.push("      const json = await res.json();");
      lines.push("      return json.data as " + resType + ";");
    }
    lines.push("    } catch (err: unknown) {");
    lines.push("      if (err instanceof ApiException) throw err;");
    lines.push(`      throw new ApiException(err instanceof Error ? err.message : String(err));`);
    lines.push("    }");
    lines.push("  }");
    lines.push("");
  }

  lines.push("}");

  return lines.join("\n");
}

function mapTypeToTs(normalized: string): string {
  switch (normalized) {
    case "integer":
    case "number":
      return "number";
    case "string":
      return "string";
    case "boolean":
      return "boolean";
    case "void":
      return "void";
    case "array":
      return "string[]";
    case "object":
      return "Record<string, unknown>";
    default:
      return "unknown";
  }
}

function capitalize(s: string): string {
  if (!s) return s;
  return s.charAt(0).toUpperCase() + s.slice(1);
}
